### ISSUE TITLE
build command is failing

### ISSUE THREAD

**Issue by nazarepiedady** [elonehoo/vitest-docs-template#2]
The build command to build the website on Netlify is failing at the moment, and something needs to be done to correct it.

**Comment by nazarepiedady** [comment]
I just changed the `netlify.toml` build command from `pnpm docs:build` to `pnpm build` because there is no `docs:build` script, and the message error showed to is:

```
5:40:21 AM: Netlify Build                                                 
5:40:21 AM: ────────────────────────────────────────────────────────────────
5:40:21 AM: ​
5:40:21 AM: ❯ Version
5:40:21 AM:   @netlify/build 29.37.2
5:40:21 AM: ​
5:40:21 AM: ❯ Flags
5:40:21 AM:   baseRelDir: true
5:40:21 AM:   buildId: 660b8c0d833e127192d809f8
5:40:21 AM:   deployId: 660b8c0d833e127192d809fa
5:40:21 AM: ​
5:40:21 AM: ❯ Current directory
5:40:21 AM:   /opt/build/repo
5:40:21 AM: ​
5:40:21 AM: ❯ Config file
5:40:21 AM:   /opt/build/repo/netlify.toml
5:40:21 AM: ​
5:40:21 AM: ❯ Context
5:40:21 AM:   production
5:40:21 AM: ​
5:40:21 AM: build.command from netlify.toml                               
5:40:21 AM: ────────────────────────────────────────────────────────────────
5:40:21 AM: ​
5:40:21 AM: $ pnpm build
5:40:21 AM: > @vitest/monorepo@1.4.0 build /opt/build/repo
5:40:21 AM: > nr prefetch && vitepress build docs
5:40:22 AM: > @vitest/monorepo@1.4.0 prefetch /opt/build/repo
5:40:22 AM: > tsx .vitepress/scripts/fetch-avatars.ts
5:40:22 AM: node:internal/process/esm_loader:34
5:40:22 AM:       internalBinding("errors").triggerUncaughtException(
5:40:22 AM:                                 ^
5:40:22 AM: Error [ERR_MODULE_NOT_FOUND]: Cannot find module "/opt/build/repo/.vitepress/scripts/fetch-avatars.ts" imported from /opt/build/repo/
5:40:22 AM:     at finalizeResolution (node:internal/modules/esm/resolve:265:11)
5:40:22 AM:     at moduleResolve (node:internal/modules/esm/resolve:933:10)
5:40:22 AM:     at defaultResolve (node:internal/modules/esm/resolve:1157:11)
5:40:22 AM:     at nextResolve (node:internal/modules/esm/hooks:866:28)
5:40:22 AM:     at d (file:///opt/build/repo/node_modules/.pnpm/tsx@4.6.1/node_modules/tsx/dist/esm/index.mjs:5:34)
5:40:22 AM:     at S (file:///opt/build/repo/node_modules/.pnpm/tsx@4.6.1/node_modules/tsx/dist/esm/index.mjs:5:1187)
5:40:22 AM:     at nextResolve (node:internal/modules/esm/hooks:866:28)
5:40:22 AM:     at Hooks.resolve (node:internal/modules/esm/hooks:304:30)
5:40:22 AM:     at handleMessage (node:internal/modules/esm/worker:196:24)
5:40:22 AM:     at Immediate.checkForMessages (node:internal/modules/esm/worker:138:28) {
5:40:22 AM:   code: "ERR_MODULE_NOT_FOUND",
5:40:22 AM:   url: "file:///opt/build/repo/.vitepress/scripts/fetch-avatars.ts"
5:40:22 AM: }
5:40:22 AM: Node.js v20.12.0
5:40:22 AM:  ELIFECYCLE  Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
5:40:22 AM:  ELIFECYCLE  Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
5:40:22 AM: ​
5:40:22 AM: "build.command" failed                                        
5:40:22 AM: ────────────────────────────────────────────────────────────────
5:40:22 AM: ​
5:40:22 AM:   Error message
5:40:22 AM:   Command failed with exit code 1: pnpm build (https://ntl.fyi/exit-code-1)
5:40:22 AM: ​
5:40:22 AM:   Error location
5:40:22 AM:   In build.command from netlify.toml:
5:40:22 AM:   pnpm build
5:40:22 AM: ​
5:40:22 AM:   Resolved config
5:40:22 AM:   build:
5:40:22 AM:     command: pnpm build
5:40:22 AM:     commandOrigin: config
5:40:22 AM:     environment:
5:40:22 AM:       - NODE_VERSION
5:40:22 AM:       - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
5:40:22 AM:     ignore: git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- docs/ package.json pnpm-lock.yaml
5:40:22 AM:     publish: /opt/build/repo/docs/.vitepress/dist
5:40:22 AM:     publishOrigin: config
5:40:22 AM:   headers:
5:40:22 AM:     - for: /manifest.webmanifest
5:40:22 AM:       values:
5:40:22 AM:         Content-Type: application/manifest+json
5:40:22 AM:   headersOrigin: config
5:40:22 AM:   redirects:
5:40:22 AM:     - from: /new
5:40:22 AM:       status: 302
5:40:22 AM:       to: https://stackblitz.com/fork/github/vitest-dev/vitest/tree/main/examples/basic?initialPath=__vitest__/
5:40:22 AM:     - from: /vscode
5:40:22 AM:       status: 302
5:40:22 AM:       to: https://marketplace.visualstudio.com/items?itemName=vitest.explorer
5:40:22 AM:   redirectsOrigin: config
5:40:22 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
5:40:23 AM: Failed during stage "building site": Build script returned non-zero exit code: 2
5:40:23 AM: Failing build: Failed to build site
5:40:23 AM: Finished processing build request in 28.305s
```

**Comment by nazarepiedady** [comment]
@elonehoo, @sheremet-va, could you give me some light?

**Comment by elonehoo** [comment]
Ah, not @[sheremet-va](https://github.com/sheremet-va) it, let's work it out between the two of us.

**Comment by nazarepiedady** [comment]
@elonehoo, what do you suggest?
I am available to do the changes and do the pull request.

**Comment by elonehoo** [comment]
sorry, that was an oversight.

this modification will pass the packaging

https://github.com/elonehoo/vitest-docs-template/commit/88b9e76d29d0ceec0dd92df3153a25bd39990be2

**Comment by elonehoo** [comment]
@nazarepiedady  thank you very much for using it, i found this template still seems to have a lot of problems, let's improve it together!

**Comment by nazarepiedady** [comment]
@elonehoo, I will close this issue since it is already solved, then I will study the template to see that could be done to improve it even more.
